name: Deploy Prisma Migrations to Supabase

# This action runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js version

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Prisma Generate
      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          # The database URL is required for generate
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # 5. Run Prisma Migrate Deploy
      - name: Deploy Prisma Migrations
        run: npx prisma migrate deploy
        env:
          # The database URL is required to connect to Supabase
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
